Can2Cloud: SIM900::Dev Class Reference
SIM900::Dev Class Reference
#include <sim900.h>
Public Member Functions
Dev (std::string APN, std::string user_name, std::string password)
Construct a new SIM900::Dev::Dev object. The constructor takes three parameters to configure the APN, and the password and username are set as 'blank' by default.
~Dev ()
Destroy the SIM900::Dev::Dev object.
Error CIPMux (AT_CIP_MUX mode)
A method for sending an AT command to set multi or single TCP/UDP connection. The method takes a AT_CIP_MUX mode parameter to select the operation mode, and returns either 'OK' or 'Fail'.
Error CIPStart (char *connection_mode, char *domain, char *port)
A method for initiating a TCP/UDP connection. The method takes three char* parameters to configure the connection and then sends a command in the format: AT_COMMAND + 'Mode' + 'IP address' + 'Port'.
Error CIPSend (const char *deviceToken, const char *field1, const char *field2, const char *field3)
A method to send data through the TCP pre-stabilish connection. The method takes three const char* parameters for populate the Tago.io fields, and returns either 'OK' or 'Fail'.
Error SimpleAT ()
A method for sending an AT command for verify the module response for AT commands. The method returns either 'OK' or 'Fail'.
Error CIPShut ()
A method for sending an AT command to shut off all the previous connections. The method returns either 'OK' or 'Fail'.
Error AttachGPRS ()
A method for sending an AT command to attach the GPRS connection. The method returns either 'OK' or 'Fail'.
Error DetachGPRS ()
A method for sending an AT command to detach the GPRS connection. The method returns either 'OK' or 'Fail'.
Error SetCFUN ()
Error SetAPN (std::string APN, std::string user_name, std::string password)
A method for sending an AT command to configure the APN settings. The method takes three parameters to specify the desired APN and returns either 'OK' or 'Fail'.
Error SetPrompt ()
A method for sending an AT command to set the prompt for writing a message. The method returns either 'OK' or 'Fail'.
Error BringUpWireless ()
A method for sending an AT command to bring up the wireless connection. The method returns either 'OK' or 'Fail'.
Error ShowIp ()
A method for sending an AT command to show up the ip address. The method returns either 'OK' or 'Fail'.
Error VerifyGPRS ()
A method for sending an AT command to verify the GPRS connection. The method returns either 'OK' or 'Fail'.
void init ()
The init method sends AT commands to configure the basic settings for a TCP connection. This method shuts off all previous connections and establishes a new GPRS connection.
Static Public Attributes
static constexpr char AT_SIMPLE [] = "AT\r\n"
static constexpr char AT_CFUN [] = "AT+CFUN=1\r\n"
static constexpr char AT_CSTT [] = "AT+CSTT="
static constexpr char AT_CIP_SPRT [] = "AT+CIPSPRT=0\r\n"
static constexpr char AT_CIICR [] = "AT+CIICR\r\n"
static constexpr char AT_CIFSR [] = "AT+CIFSR\r\n"
static constexpr char AT_CGATT_DIS [] = "AT+CGATT=0\r\n"
static constexpr char AT_CGATT_EN [] = "AT+CGATT=1\r\n"
static constexpr char AT_CIP_SHUT [] = "AT+CIPSHUT\r\n"
static constexpr char AT_CIP_SEND [] = "ATP+CIPSEND\r\n"
static constexpr char AT_CIP_START [] = "AT+CIPSTART="
static constexpr char AT_CIP_MUX_MULTI [] = "AT+CIPMUX=1\r\n"
static constexpr char AT_CIP_MUX_SINGLE [] = "AT+CIPMUX=0\r\n"
static constexpr char AT_CREG [] = "AT+CREG?\r\n"
Private Member Functions
Error send_command (const char *command)
A method to transmit commands. The method takes the const char* command as a parameter, sends it through UART bus, and returns either 'OK' or 'Fail'.
const char * createJsonString (const char *x, const char *y, const char *z)
A method that creates a string in JSON format for transmission over a TCP connection. The method takes three parameters to populate the data field and returns a const char* in JSON format.
Private Attributes
std::string APN_ = ""
std::string user_name_ = ""
std::string password_ = ""
Additional Inherited Members
Protected Member Functions inherited from UART::bus
bus ()
Construct a new UART::bus::bus object.
~bus ()
Destroy the UART::bus::bus object.
const char * send_at_command (const char *command)
Send a AT command to the SIM900.
Detailed Description
Definition at line 22 of file sim900.h.
Constructor & Destructor Documentation
Dev()
SIM900::Dev::Dev (std::string APN, std::string user_name = "", std::string password = "")
Construct a new SIM900::Dev::Dev object. The constructor takes three parameters to configure the APN, and the password and username are set as 'blank' by default.
Parameters
APN
user_name
password
Definition at line 12 of file sim900.cpp.
    : APN_(APN), user_name_(user_name), password_(password) {}
~Dev()
SIM900::Dev::~Dev ()
Destroy the SIM900::Dev::Dev object.
Definition at line 63 of file sim900.cpp.
                {
  ESP_LOGI(TAG_SIM, "DETACH: ");
  DetachGPRS();
  ESP_LOGI(TAG_SIM, "SHUT: ");
  CIPShut();
}
References TAG_SIM.
Member Function Documentation
AttachGPRS()
SIM900::Error SIM900::Dev::AttachGPRS ()
A method for sending an AT command to attach the GPRS connection. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 223 of file sim900.cpp.
{
  // Attach From GPRS Service
  SIM900::Error ret = send_command(AT_CGATT_EN);
  return ret;
}
BringUpWireless()
SIM900::Error SIM900::Dev::BringUpWireless ()
A method for sending an AT command to bring up the wireless connection. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 295 of file sim900.cpp.
{
  // Bring up wireless connection
  SIM900::Error ret = send_command(AT_CIICR);
  return ret;
}
CIPMux()
SIM900::Error SIM900::Dev::CIPMux (AT_CIP_MUX mode)
A method for sending an AT command to set multi or single TCP/UDP connection. The method takes a AT_CIP_MUX mode parameter to select the operation mode, and returns either 'OK' or 'Fail'.
Parameters
mode
Returns
SIM900::Error
Definition at line 94 of file sim900.cpp.
{
  SIM900::Error ret;
  // Select multi ip TCP/UDP Connection
  // Select single multi ip TCP/UDP Connection
  switch (mode) {
    case AT_CIP_MUX::SINGLE:
      ret = send_command(AT_CIP_MUX_SINGLE);
      break;
    case AT_CIP_MUX::MULTI:
      ret = send_command(AT_CIP_MUX_MULTI);
      break;
    default:
      ret = Error::FAIL;
      break;
  }
  return ret;
}
References SIM900::FAIL, SIM900::MULTI, and SIM900::SINGLE.
CIPSend()
SIM900::Error SIM900::Dev::CIPSend (const char * deviceToken, const char * field1, const char * field2, const char * field3)
A method to send data through the TCP pre-stabilish connection. The method takes three const char* parameters for populate the Tago.io fields, and returns either 'OK' or 'Fail'.
Parameters
deviceToken
field1
field2
field3
Returns
SIM900::Error
Definition at line 146 of file sim900.cpp.
{
  ESP_LOGI(TAG_SIM, "Start Send");
  const char* jsonData = createJsonString(field1, field2, field3);
  char postData[1024];
  snprintf(postData, sizeof(postData),
           "POST /data HTTP/1.1\r\n"
           "Host: api.tago.io\r\n"
           "Content-Type: application/json\r\n"
           "Device-Token: %s\r\n"
           "Content-Length: %d\r\n\r\n%s",
           deviceToken, strlen(jsonData), jsonData);
  send_command(AT_CIP_SEND);
  // vTaskDelay(100 / portTICK_PERIOD_MS);
  send_command(postData);
  // vTaskDelay(100 / portTICK_PERIOD_MS);
  const char ctrlZ[] = {0x1A, '\0'};
  send_command(ctrlZ);
  vTaskDelay(100 / portTICK_PERIOD_MS);
  return Error::OK;
}
References SIM900::OK, and TAG_SIM.
Referenced by send_task().
CIPShut()
SIM900::Error SIM900::Dev::CIPShut ()
A method for sending an AT command to shut off all the previous connections. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 212 of file sim900.cpp.
{
  // Close all GPRS connections
  SIM900::Error ret = send_command(AT_CIP_SHUT);
  return ret;
}
CIPStart()
SIM900::Error SIM900::Dev::CIPStart (char * connection_mode, char * domain, char * port)
A method for initiating a TCP/UDP connection. The method takes three char* parameters to configure the connection and then sends a command in the format: AT_COMMAND + 'Mode' + 'IP address' + 'Port'.
Parameters
connection_mode
domain
port
Returns
SIM900::Error
Definition at line 122 of file sim900.cpp.
{
  // Start TCP/UDP Connection -- Add "<mode>+<ip or domain>+<port>" in the
  // string
  ESP_LOGI(TAG_SIM, "Start Connection");
  std::string conn_frame;
  const std::string quota = "\"";
  conn_frame = AT_CIP_START + quota + connection_mode + quota + "," + quota +
               domain + quota + "," + quota + port + quota + "\r\n";
  SIM900::Error ret = send_command(conn_frame.c_str());
  return ret;
}
References TAG_SIM.
Referenced by app_main().
createJsonString()
const char * SIM900::Dev::createJsonString (const char * x, const char * y, const char * z) private
A method that creates a string in JSON format for transmission over a TCP connection. The method takes three parameters to populate the data field and returns a const char* in JSON format.
Parameters
x
y
z
Returns
const char*
Definition at line 180 of file sim900.cpp.
{
  size_t bufferSize = strlen(x) + strlen(y) + strlen(z) + 100;
  char* jsonBuffer = new char[bufferSize];
  snprintf(jsonBuffer, bufferSize,
           "["
           "{\"variable\":\"x\",\"value\":\"%s\"},"
           "{\"variable\":\"y\",\"value\":\"%s\"},"
           "{\"variable\":\"z\",\"value\":\"%s\"}"
           "]",
           x, y, z);
  const char* result = strdup(jsonBuffer);
  delete[] jsonBuffer;
  return result;
}
DetachGPRS()
SIM900::Error SIM900::Dev::DetachGPRS ()
A method for sending an AT command to detach the GPRS connection. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 234 of file sim900.cpp.
{
  // Detach From GPRS Service
  SIM900::Error ret = send_command(AT_CGATT_DIS);
  return ret;
}
init()
void SIM900::Dev::init ()
The init method sends AT commands to configure the basic settings for a TCP connection. This method shuts off all previous connections and establishes a new GPRS connection.
Definition at line 21 of file sim900.cpp.
                     {
  int trys = 0;
  ESP_LOGI(TAG_SIM, "AT: ");
  SimpleAT();
  vTaskDelay(500 / portTICK_PERIOD_MS);
  ESP_LOGI(TAG_SIM, "SHUT: ");
  CIPShut();
  vTaskDelay(500 / portTICK_PERIOD_MS);
  ESP_LOGI(TAG_SIM, "CIPMUX: ");
  CIPMux(AT_CIP_MUX::SINGLE);
  vTaskDelay(500 / portTICK_PERIOD_MS);
  // ESP_LOGI(TAG_SIM, "CFUN: ");
  // SetCFUN();
  // vTaskDelay(3000 / portTICK_PERIOD_MS);
  ESP_LOGI(TAG_SIM, "CGATT: ");
  while (AttachGPRS() != SIM900::Error::OK && trys <= max_try) {
    ESP_LOGI(TAG_SIM, "CGATT: CONNECT ERROR");
    trys++;
  }
  vTaskDelay(500 / portTICK_PERIOD_MS);
  ESP_LOGI(TAG_SIM, "CSTT: ");
  SetAPN(APN_, user_name_, password_);
  vTaskDelay(500 / portTICK_PERIOD_MS);
  ESP_LOGI(TAG_SIM, "CIICR: ");
  BringUpWireless();
  vTaskDelay(500 / portTICK_PERIOD_MS);
  ESP_LOGI(TAG_SIM, "CIFSR: ");
  ShowIp();
  vTaskDelay(500 / portTICK_PERIOD_MS);
}
References max_try, SIM900::OK, SIM900::SINGLE, and TAG_SIM.
Referenced by app_main().
send_command()
SIM900::Error SIM900::Dev::send_command (const char * command) private
A method to transmit commands. The method takes the const char* command as a parameter, sends it through UART bus, and returns either 'OK' or 'Fail'.
Parameters
command
Returns
SIM900::Error
Definition at line 78 of file sim900.cpp.
{
  const char* ret = send_at_command(command);
  const char* err = "ERROR";
  if (strstr(ret, err) != nullptr) {
    ESP_LOGI(TAG_SIM, "ERROR?");
    return Error::FAIL;
  }
  return Error::OK;
}
References SIM900::FAIL, SIM900::OK, and TAG_SIM.
SetAPN()
SIM900::Error SIM900::Dev::SetAPN (std::string APN, std::string user_name, std::string password)
A method for sending an AT command to configure the APN settings. The method takes three parameters to specify the desired APN and returns either 'OK' or 'Fail'.
Parameters
APN
user_name
password
Returns
SIM900::Error
Definition at line 267 of file sim900.cpp.
{
  // Start task and set APN, User and Password -- Add "<apn>","<user
  // name>","<password>"
  const std::string quota = "\"";
  std::string frame = AT_CSTT + quota + APN + quota + "," + quota + user_name +
                      quota + "," + quota + password + quota + "\r\n";
  SIM900::Error ret = send_command(frame.c_str());
  return ret;
}
SetCFUN()
SIM900::Error SIM900::Dev::SetCFUN ()
Returns
SIM900::Error
Definition at line 244 of file sim900.cpp.
{
  SIM900::Error ret = send_command(AT_CFUN);
  return ret;
}
SetPrompt()
SIM900::Error SIM900::Dev::SetPrompt ()
A method for sending an AT command to set the prompt for writing a message. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 284 of file sim900.cpp.
{
  SIM900::Error ret = send_command(AT_CIP_SPRT);
  return ret;
}
Referenced by app_main().
ShowIp()
SIM900::Error SIM900::Dev::ShowIp ()
A method for sending an AT command to show up the ip address. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 306 of file sim900.cpp.
{
  SIM900::Error ret = send_command(AT_CIFSR);
  return ret;
}
SimpleAT()
SIM900::Error SIM900::Dev::SimpleAT ()
A method for sending an AT command for verify the module response for AT commands. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 202 of file sim900.cpp.
{
  SIM900::Error ret = send_command(AT_SIMPLE);
  return ret;
}
VerifyGPRS()
SIM900::Error SIM900::Dev::VerifyGPRS ()
A method for sending an AT command to verify the GPRS connection. The method returns either 'OK' or 'Fail'.
Returns
SIM900::Error
Definition at line 254 of file sim900.cpp.
{
  SIM900::Error ret = send_command(AT_CREG);
  return ret;
}
Member Data Documentation
APN_
std::string SIM900::Dev::APN_ = "" private
Definition at line 42 of file sim900.h.
AT_CFUN
constexpr char SIM900::Dev::AT_CFUN[] = "AT+CFUN=1\r\n" static constexpr
Definition at line 25 of file sim900.h.
AT_CGATT_DIS
constexpr char SIM900::Dev::AT_CGATT_DIS[] = "AT+CGATT=0\r\n" static constexpr
Definition at line 30 of file sim900.h.
AT_CGATT_EN
constexpr char SIM900::Dev::AT_CGATT_EN[] = "AT+CGATT=1\r\n" static constexpr
Definition at line 31 of file sim900.h.
AT_CIFSR
constexpr char SIM900::Dev::AT_CIFSR[] = "AT+CIFSR\r\n" static constexpr
Definition at line 29 of file sim900.h.
AT_CIICR
constexpr char SIM900::Dev::AT_CIICR[] = "AT+CIICR\r\n" static constexpr
Definition at line 28 of file sim900.h.
AT_CIP_MUX_MULTI
constexpr char SIM900::Dev::AT_CIP_MUX_MULTI[] = "AT+CIPMUX=1\r\n" static constexpr
Definition at line 35 of file sim900.h.
AT_CIP_MUX_SINGLE
constexpr char SIM900::Dev::AT_CIP_MUX_SINGLE[] = "AT+CIPMUX=0\r\n" static constexpr
Definition at line 36 of file sim900.h.
AT_CIP_SEND
constexpr char SIM900::Dev::AT_CIP_SEND[] = "ATP+CIPSEND\r\n" static constexpr
Definition at line 33 of file sim900.h.
AT_CIP_SHUT
constexpr char SIM900::Dev::AT_CIP_SHUT[] = "AT+CIPSHUT\r\n" static constexpr
Definition at line 32 of file sim900.h.
AT_CIP_SPRT
constexpr char SIM900::Dev::AT_CIP_SPRT[] = "AT+CIPSPRT=0\r\n" static constexpr
Definition at line 27 of file sim900.h.
AT_CIP_START
constexpr char SIM900::Dev::AT_CIP_START[] = "AT+CIPSTART=" static constexpr
Definition at line 34 of file sim900.h.
AT_CREG
constexpr char SIM900::Dev::AT_CREG[] = "AT+CREG?\r\n" static constexpr
Definition at line 37 of file sim900.h.
AT_CSTT
constexpr char SIM900::Dev::AT_CSTT[] = "AT+CSTT=" static constexpr
Definition at line 26 of file sim900.h.
AT_SIMPLE
constexpr char SIM900::Dev::AT_SIMPLE[] = "AT\r\n" static constexpr
Definition at line 24 of file sim900.h.
password_
std::string SIM900::Dev::password_ = "" private
Definition at line 44 of file sim900.h.
user_name_
std::string SIM900::Dev::user_name_ = "" private
Definition at line 43 of file sim900.h.
The documentation for this class was generated from the following files:
components/gprs/include/sim900.h
components/gprs/sim900.cpp