Can2Cloud: MCP2515::Device Class Reference
MCP2515::Device Class Reference
#include <mcp2515.h>
Public Member Functions
Device (const ConfigModule &config)
Construct a new Device object.
virtual ~Device ()=default
Destroys the Device object. This destructor is virtual because the class Device is inherited from SPI::Bus. This destructor will call the destructor of the SPI::Bus class.
Error reset ()
Method to reset the MCP2515 via SPI and software.
Error setConfigMode ()
Set the Config Mode of the MCP2515.
Error setListenOnlyMode ()
Set the Listen Only Mode of the MCP2515.
Error setLoopbackMode ()
Set the Loopback Mode of the MCP2515.
Error setNormalMode ()
Set the Normal Mode of the MCP2515.
Error setSleepMode ()
Set the Sleep Mode of the MCP2515.
Error setBitrate (CanSpeed canSpeed)
Set the Bitrate of the MCP2515.
Speed of the CAN bus.
Error setBitrate (CanSpeed canSpeed, CanClock canClock)
Overload of the method setBitrate.
Speed of the CAN bus and clock of the MCP2515.
Error setClkOut (CanClockOut divisor)
Set the Clk Out of the MCP2515.
uint8_t getStatus ()
Get the Status of the MCP2515. Use the instruction READ_STATUS of the SPI.
bool checkReceive ()
This method checks if RX0IF or RX1IF is set.
bool checkError ()
This method checks if receive message.
uint8_t getErrorFlags ()
Get the Error Flags of the MCP2515. The register EFLG is read.
uint8_t getRxStatus ()
Get the RX Status of the MCP2515. Use the instruction RX_STATUS of the SPI.
Error sendMessage (TXBn txbn, CanMessage &message)
This method sends a message to the CAN bus.
Error sendMessage (CanMessage &message)
This method sends a message to the CAN bus.
Error readMessage (RXBn rxbn, CanMessage &message)
This method reads a message from the CAN bus.
Error readMessage (CanMessage &message)
This method reads a message from the CAN bus.
Private Member Functions
Error setMode (CANCTRL_REQOP_MODE mode)
Set the Mode of operation of the MCP2515.
uint8_t readRegister (Register reg)
Read the register of the MCP2515.
void readRegisters (Register reg, uint8_t *data, int n)
Read multiples registers of the MCP2515.
void setRegister (Register reg, uint8_t data)
Write in the register of the MCP2515.
void setRegisters (Register reg, const uint8_t *data, int n)
Write in multiples registers of the MCP2515.
void modifyRegister (Register reg, uint8_t mask, uint8_t data)
Modify the bits of the register of the MCP2515.
Error setFilter (RXF num, bool ext, uint32_t ulData)
Set the Filter of the MCP2515.
Error setFilterMask (MASK mask, bool ext, uint32_t ulData)
Set the Filter Mask of the MCP2515.
void prepareId (uint8_t *buffer, bool ext, uint32_t id)
Method to prepare the identifier of the message.
Static Private Attributes
static constexpr int CANCTRL_REQOP = 0xE0
Request Operation mode bits.
static constexpr int CANCTRL_ABAT
Abort All Pending Transmissions bit.
static constexpr int CANCTRL_OSM = 0x08
One-Shot Mode bit.
static constexpr int CANCTRL_CLKEN = 0x04
CLKOUT Pin Enable bit.
static constexpr int CANCTRL_CLKPRE = 0x03
CLKOUT Pin Prescaler bits.
static constexpr int CANSTAT_OPMOD = 0xE0
Operation Mode bits.
static constexpr int CANSTAT_ICOD = 0x0E
Interrupt Flag Code bits.
static constexpr int CNF3_SOF = 0x80
Start-of-Frame (SOF) signal bit.
static constexpr int TXB_EXIDE_MASK = 0x08
Extended Identifier bit.
static constexpr int DLC_MASK = 0x0F
Data Length Code bits.
static constexpr int RTR_MASK = 0x40
Remote Transmission Request bit.
static constexpr int RXBnCTRL_RXM_STD
Receive Buffer Operating mode bits standard identifier.
static constexpr int RXBnCTRL_RXM_EXT
Receive Buffer Operating mode bits extended identifier.
static constexpr int RXBnCTRL_RXM_STDEXT
static constexpr int RXBnCTRL_RXM_MASK
Receive Buffer Operating mode bits mask.
static constexpr int RXBnCTRL_RTR
Remote Transmission Request bit.
static constexpr int RXB0CTRL_BUKT = 0x04
Rollover Enable bit.
static constexpr int RXB0CTRL_FILHIT_MASK = 0x03
Filter Hit bits mask.
static constexpr int RXB1CTRL_FILHIT_MASK = 0x07
Filter Hit bits mask.
static constexpr int RXB0CTRL_FILHIT = 0x00
Filter 0 hit.
static constexpr int RXB1CTRL_FILHIT = 0x01
Filter 1 hit.
static constexpr int SIDH = 0
Standard Identifier High bits.
static constexpr int SIDL = 1
Standard Identifier Low bits.
static constexpr int EID8 = 2
Extended Identifier High bits.
static constexpr int EID0 = 3
Extended Identifier Low bits.
static constexpr int DLC = 4
Data Length Code bits.
static constexpr int DATA = 5
Data bits.
static constexpr int STAT_RXIF_MASK
Receive Interrupt Flag bit mask.
static constexpr int EFLG_ERRORMASK
Error Flag bit mask.
Additional Inherited Members
Protected Member Functions inherited from SPI::Bus
Bus (int miso, int mosi, int sclk, int cs, int host)
Construct a new Bus object.
virtual ~Bus ()
Destructor for Bus object.
esp_err_t begin (int miso, int mosi, int sclk, int cs, int host)
A function to initialize the spi bus This function initializes the spi bus and the spi device using the driver/spi_master.h from ESP32.
esp_err_t transferBytes (uint8_t registerAddress, uint8_t data, uint8_t command)
Function to transfer data through the spi bus This function transfers data through the spi bus using the driver/spi_master.h from ESP32. This function is used to write or read data.
esp_err_t transferMultiplesBytes (uint8_t registerAddress, const uint8_t *txBuffer, const uint8_t *rxBuffer, size_t dataLength, uint8_t command)
Function to transfer multiples bytes through the spi bus This function transfers multiples bytes through the spi bus using the driver/spi_master.h from ESP32. This function is used to write or read multiples bytes.
Protected Attributes inherited from SPI::Bus
spi_transaction_t transaction_
Structure of the ESP-IDF for transaction spi.
spi_transaction_t transaction_multi_
Same as transaction_ but for multiples bytes.
Detailed Description
SPI::Bus
Definition at line 306 of file mcp2515.h.
Constructor & Destructor Documentation
Device()
MCP2515::Device::Device (const ConfigModule & config)
Construct a new Device object.
Parameters
config Struct with the configuration of the MCP2515
Base class initialization I2C::Bus
Definition at line 65 of file mcp2515.cpp.
    : Bus(config.miso_pin, config.mosi_pin, config.sclk_pin, config.cs_pin,
          config.spi_interface) {
  if (reset() == Error::FAIL) {
    std::cout << "RESET FAIL" << std::endl;
    while (1) {
    }
  }
  if (setBitrate(config.speed, config.clock) == Error::FAIL) {
    std::cout << "SET BITRATE FAIL" << std::endl;
    while (1) {
    }
  }
  if (setNormalMode() == Error::FAIL) {
    std::cout << "SET NORMAL MODE FAIL" << std::endl;
    while (1) {
    }
  }
}
References config, MCP2515::FAIL, reset(), setBitrate(), and setNormalMode().
~Device()
virtual MCP2515::Device::~Device () virtual default
Destroys the Device object. This destructor is virtual because the class Device is inherited from SPI::Bus. This destructor will call the destructor of the SPI::Bus class.
Member Function Documentation
checkError()
bool MCP2515::Device::checkError ()
This method checks if receive message.
Returns
true if receive message
false if not receive message
Definition at line 201 of file mcp2515.cpp.
{
  return (getErrorFlags() & EFLG_ERRORMASK);
}
checkReceive()
bool MCP2515::Device::checkReceive ()
This method checks if RX0IF or RX1IF is set.
Returns
true if RX0IF or RX1IF is set
false if RX0IF and RX1IF is not set
Definition at line 199 of file mcp2515.cpp.
{ return (getStatus() & STAT_RXIF_MASK); }
getErrorFlags()
uint8_t MCP2515::Device::getErrorFlags ()
Get the Error Flags of the MCP2515. The register EFLG is read.
Returns
value of the register EFLG
Definition at line 205 of file mcp2515.cpp.
{
  return readRegister(Register::EFLG);
}
References MCP2515::EFLG.
getRxStatus()
uint8_t MCP2515::Device::getRxStatus ()
Get the RX Status of the MCP2515. Use the instruction RX_STATUS of the SPI.
Returns
8 bits of the RX Status
Bits 7-6: Received Message (RXB0 and RXB1)
Bits 5-4: Message Type Received
Bits 3-0: Filter Match (RXF0 - RXF5)
See also
Figure 12-9: RX STATUS INSTRUCTION of the MCP2515 datasheet
Definition at line 368 of file mcp2515.cpp.
{
  if (transferBytes(0x00, 0x00,
                    static_cast<uint8_t>(MCP2515::Instruction::RX_STATUS)) !=
      ESP_OK) {
    std::cout << "GET RX STATUS ERROR" << std::endl;
  }
  return transaction_.rx_data[0];
}
References MCP2515::RX_STATUS.
getStatus()
uint8_t MCP2515::Device::getStatus ()
Get the Status of the MCP2515. Use the instruction READ_STATUS of the SPI.
Returns
uint8_t: Status of the MCP2515
Bit 7 - CANINTF.TX2IF: Transmit Buffer 2 Empty Interrupt Flag bit
Bit 6 - TXB2CNTRL.TXREQ: Transmit Buffer 2 Request-to-Send bit
Bit 5 - CANINTF.TX1IF: Transmit Buffer 1 Empty Interrupt Flag bit
Bit 4 - TXB1CNTRL.TXREQ: Transmit Buffer 1 Request-to-Send bit
Bit 3 - CANINTF.TX0IF: Transmit Buffer 0 Empty Interrupt Flag bit
Bit 2 - TXB0CNTRL.TXREQ: Transmit Buffer 0 Request-to-Send bit
Bit 1 - CANINTF.RX1IF: Receive Buffer 1 Full Interrupt Flag bit
Bit 0 - CANINTF.RX0IF: Receive Buffer 0 Full Interrupt Flag bit
Definition at line 358 of file mcp2515.cpp.
{
  if (transferBytes(0x00, 0x00,
                    static_cast<uint8_t>(MCP2515::Instruction::READ_STATUS)) !=
      ESP_OK) {
    std::cout << "GET STATUS ERROR" << std::endl;
  }
  return transaction_.rx_data[0];
}
References MCP2515::READ_STATUS.
modifyRegister()
void MCP2515::Device::modifyRegister (Register reg, uint8_t mask, uint8_t data) private
Modify the bits of the register of the MCP2515.
Parameters
reg Register to be modified
mask Mask to be applied in the register
data Value to be written in the register
Definition at line 332 of file mcp2515.cpp.
{
  uint8_t txBuffer[] = {mask, data};
  if (transferMultiplesBytes(
          static_cast<uint8_t>(reg), txBuffer, nullptr, sizeof(txBuffer),
          static_cast<uint8_t>(MCP2515::Instruction::BIT_MODIFY)) != ESP_OK) {
    std::cout << "MODIFY REGISTER ERROR" << std::endl;
    while (1) {
    }
  }
}
References MCP2515::BIT_MODIFY.
prepareId()
void MCP2515::Device::prepareId (uint8_t * buffer, bool ext, uint32_t id) private
Method to prepare the identifier of the message.
Parameters
buffer Buffer to store the identifier
ext Flag for extended identifier
id Identifier of the message
Definition at line 236 of file mcp2515.cpp.
{
  uint16_t can_id = static_cast<uint16_t>(id & 0x0FFFF);
  if (ext) {
    buffer[EID0] = static_cast<uint8_t>(can_id & 0xFF);
    buffer[EID8] = static_cast<uint8_t>(can_id >> 8);
    can_id = static_cast<uint16_t>(id >> 16);
    buffer[SIDL] = static_cast<uint8_t>(can_id & 0x03);
    buffer[SIDL] += static_cast<uint8_t>((can_id & 0x1C) << 3);
    buffer[SIDL] |= TXB_EXIDE_MASK;
    buffer[SIDH] = static_cast<uint8_t>(can_id >> 5);
  } else {
    buffer[SIDH] = static_cast<uint8_t>(can_id >> 3);
    buffer[SIDL] = static_cast<uint8_t>((can_id & 0x07) << 5);
    buffer[EID0] = 0;
    buffer[EID8] = 0;
  }
}
readMessage() [1/2]
MCP2515::Error MCP2515::Device::readMessage (CanMessage & message)
This method reads a message from the CAN bus.
Parameters
message Message to be read
Returns
Error::OK if the message was read successfully
Error::FAIL if data length code is too long
Error::NO_MSG if there is no message to be read
Definition at line 378 of file mcp2515.cpp.
{
  uint8_t stat = getStatus();
  if (stat & static_cast<uint8_t>(STAT::RX0IF)) {
    return readMessage(RXBn::RXB0, message);
  } else if (stat & static_cast<uint8_t>(STAT::RX1IF)) {
    return readMessage(RXBn::RXB1, message);
  }
  return Error::NO_MSG;
}
References MCP2515::NO_MSG, MCP2515::RX0IF, MCP2515::RX1IF, MCP2515::RXB0, and MCP2515::RXB1.
readMessage() [2/2]
MCP2515::Error MCP2515::Device::readMessage (RXBn rxbn, CanMessage & message)
This method reads a message from the CAN bus.
Parameters
rxbn Receive buffer to be used
message Message to be read
Returns
Error::OK if the message was read successfully
Error::FAIL if data length code is too long
Definition at line 389 of file mcp2515.cpp.
{
  const RXBn_REGS* rxb = &RXB[static_cast<int>(rxbn)];
  uint8_t tbufdata[5];
  readRegisters(rxb->SIDH, tbufdata, 5);
  uint32_t id = (tbufdata[SIDH] << 3) + (tbufdata[SIDL] >> 5);
  if ((tbufdata[SIDL] & TXB_EXIDE_MASK) == TXB_EXIDE_MASK) {
    id = (id << 2) + (tbufdata[SIDL] & 0x03);
    id = (id << 8) + tbufdata[EID8];
    id = (id << 8) + tbufdata[EID0];
    id |= CAN_EFF_FLAG;
  }
  uint8_t dlc = (tbufdata[DLC] & DLC_MASK);
  if (dlc > CAN_MAX_DATA_LENGTH) {
    return Error::FAIL;
  }
  uint8_t ctrl = readRegister(rxb->CTRL);
  if (ctrl & RXBnCTRL_RTR) {
    id |= CAN_RTR_FLAG;
  }
  message.identifier = id;
  message.data_length_code = dlc;
  readRegisters(rxb->DATA, message.data, dlc);
  modifyRegister(Register::CANINTF, static_cast<int>(rxb->CANINTF_RXnIF), 0);
  return Error::OK;
}
References CAN_EFF_FLAG, CAN_MAX_DATA_LENGTH, CAN_RTR_FLAG, MCP2515::CANINTF, MCP2515::RXBn_REGS::CANINTF_RXnIF, MCP2515::RXBn_REGS::CTRL, CanMessage::data, MCP2515::RXBn_REGS::DATA, CanMessage::data_length_code, MCP2515::FAIL, CanMessage::identifier, MCP2515::OK, RXB, and MCP2515::RXBn_REGS::SIDH.
readRegister()
uint8_t MCP2515::Device::readRegister (Register reg) private
Read the register of the MCP2515.
Parameters
reg Register to be read
Returns
value of the register
This function uses the I2C::Bus::transferBytes() function to read a single byte from the MCP2515 register.
Definition at line 219 of file mcp2515.cpp.
{
  if (transferBytes(static_cast<uint8_t>(reg), 0x00,
                    static_cast<uint8_t>(MCP2515::Instruction::READ)) !=
      ESP_OK) {
    std::cout << "READ ERROR" << std::endl;
    while (1) {
    }
  }
  return transaction_.rx_data[0];
}
References MCP2515::READ.
readRegisters()
void MCP2515::Device::readRegisters (Register reg, uint8_t * data, int n) private
Read multiples registers of the MCP2515.
Parameters
reg First register to be read
data Buffer to store the data
n Number of registers to be read
Definition at line 322 of file mcp2515.cpp.
{
  if (transferMultiplesBytes(
          static_cast<uint8_t>(reg), nullptr, data, n,
          static_cast<uint8_t>(MCP2515::Instruction::READ)) != ESP_OK) {
    std::cout << "READ REGISTERS ERROR" << std::endl;
    while (1) {
    }
  }
}
References MCP2515::READ.
reset()
MCP2515::Error MCP2515::Device::reset ()
Method to reset the MCP2515 via SPI and software.
Returns
Error::OK if the reset was successful
Error::FAIL if the reset was not successful
Definition at line 90 of file mcp2515.cpp.
{
  if (transferBytes(0x00, 0x00,
                    static_cast<uint8_t>(MCP2515::Instruction::RESET)) !=
      ESP_OK) {
    std::cout << "RESET ERROR" << std::endl;
    return Error::FAIL;
  }
  vTaskDelay(10 / portTICK_PERIOD_MS);
  setRegister(Register::TXB0CTRL, 0x00);
  setRegister(Register::TXB1CTRL, 0x00);
  setRegister(Register::TXB2CTRL, 0x00);
  setRegister(Register::RXB0CTRL, 0x00);
  setRegister(Register::RXB1CTRL, 0x00);
  setRegister(Register::CANINTE, static_cast<int>(CANINTF::RX0IF) |
                                     static_cast<int>(CANINTF::RX1IF) |
                                     static_cast<int>(CANINTF::ERRIF) |
                                     static_cast<int>(CANINTF::MERRF));
  modifyRegister(Register::RXB0CTRL,
                 RXBnCTRL_RXM_MASK | RXB0CTRL_BUKT | RXB0CTRL_FILHIT_MASK,
                 RXBnCTRL_RXM_STDEXT | RXB0CTRL_BUKT | RXB0CTRL_FILHIT);
  modifyRegister(Register::RXB1CTRL, RXBnCTRL_RXM_MASK | RXB1CTRL_FILHIT_MASK,
                 RXBnCTRL_RXM_STDEXT | RXB1CTRL_FILHIT);
  RXF filters[] = {RXF::RXF0, RXF::RXF1, RXF::RXF2,
                   RXF::RXF3, RXF::RXF4, RXF::RXF5};
  for (int i = 0; i < 6; i++) {
    bool ext = (i == 1);
    if (setFilter(filters[i], ext, 0) != Error::OK) {
      return Error::FAIL;
    }
  }
  MCP2515::MASK masks[] = {MASK::MASK0, MASK::MASK1};
  for (int i = 0; i < 2; i++) {
    if (setFilterMask(masks[i], true, 0) != Error::OK) {
      return Error::FAIL;
    }
  }
  return Error::OK;
}
References MCP2515::CANINTE, MCP2515::ERRIF, MCP2515::FAIL, MCP2515::MASK0, MCP2515::MASK1, MCP2515::MERRF, MCP2515::OK, MCP2515::RESET, MCP2515::RX0IF, MCP2515::RX1IF, MCP2515::RXB0CTRL, MCP2515::RXB1CTRL, MCP2515::RXF0, MCP2515::RXF1, MCP2515::RXF2, MCP2515::RXF3, MCP2515::RXF4, MCP2515::RXF5, MCP2515::TXB0CTRL, MCP2515::TXB1CTRL, and MCP2515::TXB2CTRL.
Referenced by Device().
sendMessage() [1/2]
MCP2515::Error MCP2515::Device::sendMessage (CanMessage & message)
This method sends a message to the CAN bus.
Parameters
message Message to be sent
Returns
Error::OK if the message was sent successfully
Error::FAIL_TX if data length code is too long
Error::ALL_TX_BUSY if all transmit buffers are busy
Definition at line 425 of file mcp2515.cpp.
{
  if (message.data_length_code > CAN_MAX_DATA_LENGTH) {
    return Error::FAIL_TX;
  }
  TXBn txBuffers[N_TXBUFFERS] = {TXBn::TXB0, TXBn::TXB1, TXBn::TXB2};
  for (int i = 0; i < N_TXBUFFERS; i++) {
    const TXBn_REGS* txbuf = &TXB[static_cast<int>(txBuffers[i])];
    uint8_t ctrlval = readRegister(txbuf->CTRL);
    if ((ctrlval & static_cast<int>(TXBnCTRL::TXREQ)) == 0) {
      return sendMessage(txBuffers[i], message);
    }
  }
  return Error::ALL_TX_BUSY;
}
References MCP2515::ALL_TX_BUSY, CAN_MAX_DATA_LENGTH, MCP2515::TXBn_REGS::CTRL, CanMessage::data_length_code, MCP2515::FAIL_TX, MCP2515::N_TXBUFFERS, TXB, MCP2515::TXB0, MCP2515::TXB1, MCP2515::TXB2, and MCP2515::TXREQ.
sendMessage() [2/2]
MCP2515::Error MCP2515::Device::sendMessage (TXBn txbn, CanMessage & message)
This method sends a message to the CAN bus.
Parameters
txbn Transmit buffer to be used
message Message to be sent
Returns
Error::OK if the message was sent successfully
Error::FAIL_TX if data length code is too long
Definition at line 443 of file mcp2515.cpp.
{
  if (message.data_length_code > CAN_MAX_DATA_LENGTH) {
    return Error::FAIL_TX;
  }
  const TXBn_REGS* txbuf = &TXB[static_cast<int>(txbn)];
  uint8_t data[13];
  bool ext = (message.identifier & CAN_EFF_FLAG);
  bool rtr = (message.identifier & CAN_RTR_FLAG);
  uint32_t id = (message.identifier & (ext ? CAN_EFF_MASK : CAN_SFF_MASK));
  prepareId(data, ext, id);
  data[DLC] =
      rtr ? (message.data_length_code | RTR_MASK) : message.data_length_code;
  memcpy(&data[DATA], message.data, message.data_length_code);
  setRegisters(txbuf->SIDH, data, 5 + message.data_length_code);
  modifyRegister(txbuf->CTRL, static_cast<int>(TXBnCTRL::TXREQ),
                 static_cast<int>(TXBnCTRL::TXREQ));
  uint8_t ctrl = readRegister(txbuf->CTRL);
  if ((ctrl &
       (static_cast<int>(TXBnCTRL::ABTF) | static_cast<int>(TXBnCTRL::MLOA) |
        static_cast<int>(TXBnCTRL::TXERR))) != 0) {
    return Error::FAIL_TX;
  }
  return Error::OK;
}
References MCP2515::ABTF, CAN_EFF_FLAG, CAN_EFF_MASK, CAN_MAX_DATA_LENGTH, CAN_RTR_FLAG, CAN_SFF_MASK, MCP2515::TXBn_REGS::CTRL, CanMessage::data, CanMessage::data_length_code, MCP2515::FAIL_TX, CanMessage::identifier, MCP2515::MLOA, MCP2515::OK, MCP2515::TXBn_REGS::SIDH, TXB, MCP2515::TXERR, and MCP2515::TXREQ.
setBitrate() [1/2]
MCP2515::Error MCP2515::Device::setBitrate (CanSpeed canSpeed)
Set the Bitrate of the MCP2515.
Speed of the CAN bus.
Parameters
canSpeed Speed of the CAN bus
Returns
Error::OK if the bitrate was set successfully
Error::FAIL if the bitrate was not set successfully
Definition at line 157 of file mcp2515.cpp.
{
  return setBitrate(canSpeed, CanClock::k16MHZ);
}
References MCP2515::k16MHZ.
Referenced by Device().
setBitrate() [2/2]
MCP2515::Error MCP2515::Device::setBitrate (CanSpeed canSpeed, CanClock canClock)
Overload of the method setBitrate.
Speed of the CAN bus and clock of the MCP2515.
Parameters
canSpeed Speed of the CAN bus
canClock Clock of the MCP2515. Default 16MHz
Returns
Error::OK if the bitrate was set successfully
Error::FAIL if the bitrate was not set successfully
Definition at line 161 of file mcp2515.cpp.
{
  Error error = setConfigMode();
  if (error != Error::OK) {
    std::cout << "ERROR SETTING CONFIG MODE" << std::endl;
    return error;
  }
  const auto& config = __configMap.find({canClock, canSpeed});
  if (config == __configMap.end()) {
    return Error::FAIL;
  }
  setRegister(Register::CNF1,
              static_cast<uint8_t>(std::get<0>(config->second)));
  setRegister(Register::CNF2,
              static_cast<uint8_t>(std::get<1>(config->second)));
  setRegister(Register::CNF3,
              static_cast<uint8_t>(std::get<2>(config->second)));
  return Error::OK;
}
References __configMap, MCP2515::CNF1, MCP2515::CNF2, MCP2515::CNF3, config, MCP2515::FAIL, and MCP2515::OK.
setClkOut()
MCP2515::Error MCP2515::Device::setClkOut (MCP2515::CanClockOut divisor)
Set the Clk Out of the MCP2515.
Parameters
divisor Divisor of the clock out
Returns
Error::OK if the clock out was set successfully
Error::FAIL if the clock out was not set successfully
Definition at line 182 of file mcp2515.cpp.
{
  if (divisor == CanClockOut::DISABLE) {
    modifyRegister(Register::CANCTRL, CANCTRL_CLKEN, 0x00);  // Turn off CLKEN
    modifyRegister(Register::CNF3, CNF3_SOF,
                   CNF3_SOF);  // Turn on CLKOUT for SOF
    return Error::OK;
  }
  modifyRegister(Register::CANCTRL, CANCTRL_CLKPRE,
                 static_cast<int>(divisor));  // Set the prescaler (CLKPRE)
  modifyRegister(Register::CANCTRL, CANCTRL_CLKEN,
                 CANCTRL_CLKEN);                   // Turn on CLKEN
  modifyRegister(Register::CNF3, CNF3_SOF, 0x00);  // Turn off CLKOUT for SOF
  return Error::OK;
}
References MCP2515::CANCTRL, MCP2515::CNF3, MCP2515::DISABLE, and MCP2515::OK.
setConfigMode()
MCP2515::Error MCP2515::Device::setConfigMode ()
Set the Config Mode of the MCP2515.
Returns
Error::OK if the mode was set successfully
Error::FAIL if the mode was not set successfully
Definition at line 137 of file mcp2515.cpp.
{
  return setMode(CANCTRL_REQOP_MODE::CONFIG);
}
References MCP2515::CONFIG.
setFilter()
MCP2515::Error MCP2515::Device::setFilter (RXF num, bool ext, uint32_t ulData) private
Set the Filter of the MCP2515.
Parameters
num Number of the filter
ext Extended identifier
ulData Data to be set
Returns
Error::OK if the filter was set successfully
Error::FAIL if the filter was not set successfully
Definition at line 278 of file mcp2515.cpp.
{
  setConfigMode();
  Register reg;
  switch (num) {
    case RXF::RXF0:
      reg = Register::RXF0SIDH;
      break;
    case RXF::RXF1:
      reg = Register::RXF1SIDH;
      break;
    case RXF::RXF2:
      reg = Register::RXF2SIDH;
      break;
    case RXF::RXF3:
      reg = Register::RXF3SIDH;
      break;
    case RXF::RXF4:
      reg = Register::RXF4SIDH;
      break;
    case RXF::RXF5:
      reg = Register::RXF5SIDH;
      break;
    default:
      return Error::FAIL;
      break;
  }
  uint8_t tbufdata[4];
  prepareId(tbufdata, ext, ulData);
  setRegisters(reg, tbufdata, 4);
  return Error::OK;
}
References MCP2515::FAIL, MCP2515::OK, MCP2515::RXF0, MCP2515::RXF0SIDH, MCP2515::RXF1, MCP2515::RXF1SIDH, MCP2515::RXF2, MCP2515::RXF2SIDH, MCP2515::RXF3, MCP2515::RXF3SIDH, MCP2515::RXF4, MCP2515::RXF4SIDH, MCP2515::RXF5, and MCP2515::RXF5SIDH.
setFilterMask()
MCP2515::Error MCP2515::Device::setFilterMask (MASK mask, bool ext, uint32_t ulData) private
Set the Filter Mask of the MCP2515.
Parameters
mask Mask to be set
ext Extended identifier
ulData Data to be set
Returns
Error::OK if the filter mask was set successfully
Error::FAIL if the filter mask was not set successfully
Definition at line 256 of file mcp2515.cpp.
{
  setConfigMode();
  uint8_t tbufdata[4];
  prepareId(tbufdata, ext, ulData);
  Register reg;
  switch (mask) {
    case MASK::MASK0:
      reg = Register::RXM0SIDH;
      break;
    case MASK::MASK1:
      reg = Register::RXM1SIDH;
      break;
    default:
      return Error::FAIL;
      break;
  }
  setRegisters(reg, tbufdata, 4);
  return Error::OK;
}
References MCP2515::FAIL, MCP2515::MASK0, MCP2515::MASK1, MCP2515::OK, MCP2515::RXM0SIDH, and MCP2515::RXM1SIDH.
setListenOnlyMode()
MCP2515::Error MCP2515::Device::setListenOnlyMode ()
Set the Listen Only Mode of the MCP2515.
Returns
Error::OK if the mode was set successfully
Error::FAIL if the mode was not set successfully
Definition at line 141 of file mcp2515.cpp.
{
  return setMode(CANCTRL_REQOP_MODE::LISTENONLY);
}
References MCP2515::LISTENONLY.
setLoopbackMode()
MCP2515::Error MCP2515::Device::setLoopbackMode ()
Set the Loopback Mode of the MCP2515.
Returns
Error::OK if the mode was set successfully
Error::FAIL if the mode was not set successfully
Definition at line 145 of file mcp2515.cpp.
{
  return setMode(CANCTRL_REQOP_MODE::LOOPBACK);
}
References MCP2515::LOOPBACK.
setMode()
MCP2515::Error MCP2515::Device::setMode (CANCTRL_REQOP_MODE mode) private
Set the Mode of operation of the MCP2515.
Parameters
mode mode of operation
Returns
Error::OK if the mode was set successfully
Error::FAIL if the mode was not set successfully
Definition at line 344 of file mcp2515.cpp.
{
  modifyRegister(Register::CANCTRL, CANCTRL_REQOP, static_cast<int>(mode));
  for (int i = 0; i < 10; i++) {
    uint8_t new_mode = readRegister(Register::CANSTAT);
    new_mode &= CANSTAT_OPMOD;
    if (new_mode == static_cast<uint8_t>(mode)) {
      return Error::OK;
    }
    vTaskDelay(10 / portTICK_PERIOD_MS);
  }
  return Error::FAIL;
}
References MCP2515::CANCTRL, MCP2515::CANSTAT, MCP2515::FAIL, and MCP2515::OK.
setNormalMode()
MCP2515::Error MCP2515::Device::setNormalMode ()
Set the Normal Mode of the MCP2515.
Returns
Error::OK if the mode was set successfully
Error::FAIL if the mode was not set successfully
Definition at line 149 of file mcp2515.cpp.
{
  return setMode(CANCTRL_REQOP_MODE::NORMAL);
}
References MCP2515::NORMAL.
Referenced by Device().
setRegister()
void MCP2515::Device::setRegister (Register reg, uint8_t data) private
Write in the register of the MCP2515.
Parameters
reg Register to be written
data Value to be written in the register
Definition at line 209 of file mcp2515.cpp.
{
  if (transferBytes(static_cast<uint8_t>(reg), data,
                    static_cast<uint8_t>(MCP2515::Instruction::WRITE)) !=
      ESP_OK) {
    std::cout << "SET REGISTER ERROR" << std::endl;
    while (1) {
    }
  }
}
References MCP2515::WRITE.
setRegisters()
void MCP2515::Device::setRegisters (Register reg, const uint8_t * data, int n) private
Write in multiples registers of the MCP2515.
Parameters
reg First register to be written
data Buffer with the data to be written
n Number of registers to be written
Definition at line 312 of file mcp2515.cpp.
{
  if (transferMultiplesBytes(
          static_cast<uint8_t>(reg), data, nullptr, n,
          static_cast<uint8_t>(MCP2515::Instruction::WRITE)) != ESP_OK) {
    std::cout << "SET REGISTERS ERROR" << std::endl;
    while (1) {
    }
  }
}
References MCP2515::WRITE.
setSleepMode()
MCP2515::Error MCP2515::Device::setSleepMode ()
Set the Sleep Mode of the MCP2515.
Returns
Error::OK if the mode was set successfully
Error::FAIL if the mode was not set successfully
Definition at line 153 of file mcp2515.cpp.
{
  return setMode(CANCTRL_REQOP_MODE::SLEEP);
}
References MCP2515::SLEEP.
Member Data Documentation
CANCTRL_ABAT
constexpr int MCP2515::Device::CANCTRL_ABAT static constexpr private
Initial value:
=
      0x10
Abort All Pending Transmissions bit.
Definition at line 309 of file mcp2515.h.
CANCTRL_CLKEN
constexpr int MCP2515::Device::CANCTRL_CLKEN = 0x04 static constexpr private
CLKOUT Pin Enable bit.
Definition at line 312 of file mcp2515.h.
CANCTRL_CLKPRE
constexpr int MCP2515::Device::CANCTRL_CLKPRE = 0x03 static constexpr private
CLKOUT Pin Prescaler bits.
Definition at line 313 of file mcp2515.h.
CANCTRL_OSM
constexpr int MCP2515::Device::CANCTRL_OSM = 0x08 static constexpr private
One-Shot Mode bit.
Definition at line 311 of file mcp2515.h.
CANCTRL_REQOP
constexpr int MCP2515::Device::CANCTRL_REQOP = 0xE0 static constexpr private
Request Operation mode bits.
Definition at line 308 of file mcp2515.h.
CANSTAT_ICOD
constexpr int MCP2515::Device::CANSTAT_ICOD = 0x0E static constexpr private
Interrupt Flag Code bits.
Definition at line 315 of file mcp2515.h.
CANSTAT_OPMOD
constexpr int MCP2515::Device::CANSTAT_OPMOD = 0xE0 static constexpr private
Operation Mode bits.
Definition at line 314 of file mcp2515.h.
CNF3_SOF
constexpr int MCP2515::Device::CNF3_SOF = 0x80 static constexpr private
Start-of-Frame (SOF) signal bit.
Definition at line 317 of file mcp2515.h.
DATA
constexpr int MCP2515::Device::DATA = 5 static constexpr private
Data bits.
Definition at line 345 of file mcp2515.h.
DLC
constexpr int MCP2515::Device::DLC = 4 static constexpr private
Data Length Code bits.
Definition at line 344 of file mcp2515.h.
DLC_MASK
constexpr int MCP2515::Device::DLC_MASK = 0x0F static constexpr private
Data Length Code bits.
Definition at line 320 of file mcp2515.h.
EFLG_ERRORMASK
constexpr int MCP2515::Device::EFLG_ERRORMASK static constexpr private
Initial value:
=
      static_cast<int>(EFLG::RX1OVR) | static_cast<int>(EFLG::RX0OVR) |
      static_cast<int>(EFLG::TXBO) | static_cast<int>(EFLG::TXEP) |
      static_cast<int>(EFLG::RXEP)
Error Flag bit mask.
Definition at line 351 of file mcp2515.h.
EID0
constexpr int MCP2515::Device::EID0 = 3 static constexpr private
Extended Identifier Low bits.
Definition at line 343 of file mcp2515.h.
EID8
constexpr int MCP2515::Device::EID8 = 2 static constexpr private
Extended Identifier High bits.
Definition at line 342 of file mcp2515.h.
RTR_MASK
constexpr int MCP2515::Device::RTR_MASK = 0x40 static constexpr private
Remote Transmission Request bit.
Definition at line 321 of file mcp2515.h.
RXB0CTRL_BUKT
constexpr int MCP2515::Device::RXB0CTRL_BUKT = 0x04 static constexpr private
Rollover Enable bit.
Definition at line 334 of file mcp2515.h.
RXB0CTRL_FILHIT
constexpr int MCP2515::Device::RXB0CTRL_FILHIT = 0x00 static constexpr private
Filter 0 hit.
Definition at line 337 of file mcp2515.h.
RXB0CTRL_FILHIT_MASK
constexpr int MCP2515::Device::RXB0CTRL_FILHIT_MASK = 0x03 static constexpr private
Filter Hit bits mask.
Definition at line 335 of file mcp2515.h.
RXB1CTRL_FILHIT
constexpr int MCP2515::Device::RXB1CTRL_FILHIT = 0x01 static constexpr private
Filter 1 hit.
Definition at line 338 of file mcp2515.h.
RXB1CTRL_FILHIT_MASK
constexpr int MCP2515::Device::RXB1CTRL_FILHIT_MASK = 0x07 static constexpr private
Filter Hit bits mask.
Definition at line 336 of file mcp2515.h.
RXBnCTRL_RTR
constexpr int MCP2515::Device::RXBnCTRL_RTR static constexpr private
Initial value:
=
      0x08
Remote Transmission Request bit.
Definition at line 332 of file mcp2515.h.
RXBnCTRL_RXM_EXT
constexpr int MCP2515::Device::RXBnCTRL_RXM_EXT static constexpr private
Initial value:
=
      0x40
Receive Buffer Operating mode bits extended identifier.
Definition at line 325 of file mcp2515.h.
RXBnCTRL_RXM_MASK
constexpr int MCP2515::Device::RXBnCTRL_RXM_MASK static constexpr private
Initial value:
=
      0x60
Receive Buffer Operating mode bits mask.
Definition at line 330 of file mcp2515.h.
RXBnCTRL_RXM_STD
constexpr int MCP2515::Device::RXBnCTRL_RXM_STD static constexpr private
Initial value:
=
      0x20
Receive Buffer Operating mode bits standard identifier.
Definition at line 323 of file mcp2515.h.
RXBnCTRL_RXM_STDEXT
constexpr int MCP2515::Device::RXBnCTRL_RXM_STDEXT static constexpr private
Initial value:
=
      0x00
Receive Buffer Operating mode bits standard or extended identifier
Definition at line 327 of file mcp2515.h.
SIDH
constexpr int MCP2515::Device::SIDH = 0 static constexpr private
Standard Identifier High bits.
Definition at line 340 of file mcp2515.h.
SIDL
constexpr int MCP2515::Device::SIDL = 1 static constexpr private
Standard Identifier Low bits.
Definition at line 341 of file mcp2515.h.
STAT_RXIF_MASK
constexpr int MCP2515::Device::STAT_RXIF_MASK static constexpr private
Initial value:
=
      static_cast<int>(STAT::RX0IF) |
      static_cast<int>(STAT::RX1IF)
Receive Interrupt Flag bit mask.
Definition at line 347 of file mcp2515.h.
TXB_EXIDE_MASK
constexpr int MCP2515::Device::TXB_EXIDE_MASK = 0x08 static constexpr private
Extended Identifier bit.
Definition at line 319 of file mcp2515.h.
The documentation for this class was generated from the following files:
components/mcp2515/include/mcp2515.h
components/mcp2515/mcp2515.cpp