Can2Cloud: MPU6050::Device Class Reference
MPU6050::Device Class Reference
Class to handle MPU6050 communication with I2C::Bus inheritance.
#include <mpu6050.h>
Public Member Functions
Device (ConfigMPU6050 &config)
Construct a new Device object.
virtual ~Device ()=default
Destroy the Device object.
void reset ()
Reset all registers to default values.
bool isConnected ()
Check if the MPU6050 is connected.
void wakeUp ()
Wake up the MPU6050.
void sleep ()
Put the MPU6050 to sleep.
AxisAccel const & getAcceleration ()
Get the Acceleration object.
Private Member Functions
bool init ()
Initialize the MPU6050.
uint8_t readRegister (Register reg)
Read a register.
uint8_t readBitField (Register reg, uint8_t start_bit, uint8_t length)
Read a bit field of a register.
esp_err_t readBlock (Register reg, uint8_t *data, uint32_t length)
Read a block of data.
esp_err_t writeRegister (Register reg, uint8_t data)
Write a register.
esp_err_t writeBitField (Register reg, uint8_t start_bit, uint8_t length, uint8_t data)
Write a bit field of a register.
esp_err_t writeBit (Register reg, uint8_t bit_num, bool data)
Write a bit to a register.
void writeSleep (bool sleep)
Put the MPU6050 to sleep or wake up.
void readAcceleration ()
Read the acceleration data.
Private Attributes
ConfigMPU6050 config_
Configuration of the MPU6050.
AxisAccel acceleration_
Acceleration data.
uint32_t acc_scale_ = 0
Acceleration scale.
double gyro_scale_ = 0
Gyroscope scale.
Additional Inherited Members
Protected Member Functions inherited from I2C::Bus
Bus (i2c_port_t port, gpio_num_t sda, gpio_num_t scl, uint32_t clk_speed)
Construct a new Bus object.
virtual ~Bus ()
Destroy the Bus object. It will delete the I2C controller.
esp_err_t init ()
A initialization function to configure the I2C controller.
esp_err_t writeRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t tx_data)
Method to write a byte to a register. It will write a byte to a register of a device connected to the I2C bus.
esp_err_t writeRegisterMultipleBytes (uint8_t dev_addr, uint8_t reg_addr, uint8_t *tx_data, uint32_t length)
Method to write multiple bytes to a register. It will write multiple bytes to a register of a device connected to the I2C bus. TODO: Implement this method.
esp_err_t writeBitRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t bit_num, bool data)
Method to write a bit to a register. It will write a bit to a register of a device connected to the I2C bus.
esp_err_t writeBitField (uint8_t dev_addr, uint8_t reg_addr, uint8_t start_bit, uint8_t length, uint8_t data)
Method to write a bit field to a register. It will write a bit field to a register of a device connected to the I2C bus.
uint8_t readRegister (uint8_t dev_addr, uint8_t reg_addr)
method to read a byte from a register. It will read a byte from a register of a device connected to the I2C bus.
esp_err_t readRegisterMultipleBytes (uint8_t dev_addr, uint8_t reg_addr, uint8_t *rx_data, uint32_t length)
Method to read multiple bytes from a register. It will read multiple bytes from a register of a device connected to the I2C bus.
uint8_t readBitFieldFromRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t start_bit, uint8_t length)
Method to read a bit field from a register. It will read a bit field from a register of a device connected to the I2C bus.
esp_err_t readWord (uint8_t dev_addr, uint8_t reg_addr, uint16_t *rx_data)
Method to read a word from a register. It will read a word from a register of a device connected to the I2C bus.
gpio_num_t getSda () const
Get the sda pin number.
gpio_num_t getScl () const
Get the scl pin number.
uint32_t getClkSpeed () const
Get the Clk Speed value.
Detailed Description
Class to handle MPU6050 communication with I2C::Bus inheritance.
Definition at line 112 of file mpu6050.h.
Constructor & Destructor Documentation
Device()
MPU6050::Device::Device (ConfigMPU6050 & config)
Construct a new Device object.
Construct a new MPU6050::Device::Device object.
Parameters
config Configuration of the MPU6050
config configuration of the MPU6050
Definition at line 19 of file mpu6050.cpp.
    : I2C::Bus(config.port, config.sda, config.scl, config.clk_speed),
      config_(config) {
  if (init()) {
    ESP_LOGI("MPU6050", "Initialized MPU6050");
  } else {
    ESP_LOGE("MPU6050", "Failed to initialize MPU6050");
  }
}
References init().
~Device()
virtual MPU6050::Device::~Device () virtual default
Destroy the Device object.
Member Function Documentation
getAcceleration()
AxisAccel const & MPU6050::Device::getAcceleration () inline
Get the Acceleration object.
Returns
AxisAccel const&
Definition at line 165 of file mpu6050.h.
{
    readAcceleration();
    return acceleration_;
  };
References acceleration_, and readAcceleration().
Referenced by vTaskAccel().
init()
bool MPU6050::Device::init () private
Initialize the MPU6050.
Returns
true
false
Definition at line 29 of file mpu6050.cpp.
{
  if (!isConnected()) {
    return false;
  }
  acc_scale_ = 32768 / (2 << static_cast<uint32_t>(config_.accel_full_scale));
  gyro_scale_ = 262 / (2 << static_cast<uint32_t>(config_.gyro_full_scale));
  wakeUp();
  // Set accelerometer range
  writeBitField(MPU6050::Register::ACCELCONFIG,
                kAccelerometerRegisterAccelConfig_FullScaleStartBit,
                kAccelerometerRegisterAccelConfig_FullScaleLength,
                static_cast<uint8_t>(config_.accel_full_scale));
  // Set gyroscope range
  writeBitField(MPU6050::Register::GYROCONFIG,
                kAccelorometerRegisterGyroConfig_FullScaleStartBit,
                kAccelorometerRegisterGyroConfig_FullScaleLength,
                static_cast<uint8_t>(config_.gyro_full_scale));
  return true;
}
References MPU6050::ACCELCONFIG, MPU6050::GYROCONFIG, kAccelerometerRegisterAccelConfig_FullScaleLength, kAccelerometerRegisterAccelConfig_FullScaleStartBit, kAccelorometerRegisterGyroConfig_FullScaleLength, and kAccelorometerRegisterGyroConfig_FullScaleStartBit.
Referenced by Device().
isConnected()
bool MPU6050::Device::isConnected ()
Check if the MPU6050 is connected.
Returns
true if connected
false if not connected
Definition at line 53 of file mpu6050.cpp.
{
  return readBitField(MPU6050::Register::WHOAMI,
                      kAccelerometerRegisterWhoAmI_StartBit,
                      kAccelerometerRegisterWhoAmI_Length) == kDeviceId;
}
References kAccelerometerRegisterWhoAmI_Length, kAccelerometerRegisterWhoAmI_StartBit, kDeviceId, and MPU6050::WHOAMI.
readAcceleration()
void MPU6050::Device::readAcceleration () private
Read the acceleration data.
Definition at line 101 of file mpu6050.cpp.
{
  uint8_t data[6];
  readBlock(MPU6050::Register::XOUTH, data, 6);
  acceleration_.x = (data[0] << 8) | data[1];
  acceleration_.y = (data[2] << 8) | data[3];
  acceleration_.z = (data[4] << 8) | data[5];
}
References MPU6050::XOUTH.
Referenced by getAcceleration().
readBitField()
uint8_t MPU6050::Device::readBitField (Register reg, uint8_t start_bit, uint8_t length) private
Read a bit field of a register.
Parameters
reg a register address
start_bit start bit of the field
length length of the field
Returns
uint8_t: a value of the field
Definition at line 63 of file mpu6050.cpp.
{
  return I2C::Bus::readBitFieldFromRegister(
      kDeviceAddress, static_cast<uint8_t>(reg), start_bit, length);
}
References kDeviceAddress, and I2C::Bus::readBitFieldFromRegister().
readBlock()
esp_err_t MPU6050::Device::readBlock (Register reg, uint8_t * data, uint32_t length) private
Read a block of data.
Parameters
reg register address
data pointer to store the data
length length of the block to read
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 69 of file mpu6050.cpp.
{
  return I2C::Bus::readRegisterMultipleBytes(
      kDeviceAddress, static_cast<uint8_t>(reg), data, length);
}
References kDeviceAddress, and I2C::Bus::readRegisterMultipleBytes().
readRegister()
uint8_t MPU6050::Device::readRegister (Register reg) private
Read a register.
Parameters
reg Register address
Returns
uint8_t: a value of the register
Definition at line 59 of file mpu6050.cpp.
{
  return I2C::Bus::readRegister(kDeviceAddress, static_cast<uint8_t>(reg));
}
References kDeviceAddress, and I2C::Bus::readRegister().
reset()
void MPU6050::Device::reset ()
Reset all registers to default values.
Note
This method writes bit 7 of the PWRMGMT1 register to 1
See also
Section 4.28 of the datasheet: https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Register-Map1.pdf
Definition at line 96 of file mpu6050.cpp.
{
  writeBit(MPU6050::Register::PWRMGMT1,
           kAccelerometerRegisterPwrMgmt1_DeviceResetBit, true);
}
References kAccelerometerRegisterPwrMgmt1_DeviceResetBit, and MPU6050::PWRMGMT1.
sleep()
void MPU6050::Device::sleep () inline
Put the MPU6050 to sleep.
Definition at line 158 of file mpu6050.h.
{ writeSleep(true); };
References writeSleep().
wakeUp()
void MPU6050::Device::wakeUp () inline
Wake up the MPU6050.
Definition at line 152 of file mpu6050.h.
{ writeSleep(false); };
References writeSleep().
writeBit()
esp_err_t MPU6050::Device::writeBit (Register reg, uint8_t bit_num, bool data) private
Write a bit to a register.
Parameters
reg register address
bit_num number of the bit to write
data data to write
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 86 of file mpu6050.cpp.
{
  return I2C::Bus::writeBitRegister(kDeviceAddress, static_cast<uint8_t>(reg),
                                    bit_num, data);
}
References kDeviceAddress, and I2C::Bus::writeBitRegister().
writeBitField()
esp_err_t MPU6050::Device::writeBitField (Register reg, uint8_t start_bit, uint8_t length, uint8_t data) private
Write a bit field of a register.
Parameters
reg register address
start_bit start bit of the field
length length of the field
data data to write
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 80 of file mpu6050.cpp.
{
  return I2C::Bus::writeBitField(kDeviceAddress, static_cast<uint8_t>(reg),
                                 start_bit, length, data);
}
References kDeviceAddress, and I2C::Bus::writeBitField().
writeRegister()
esp_err_t MPU6050::Device::writeRegister (Register reg, uint8_t data) private
Write a register.
Parameters
reg register address
data data to write
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 75 of file mpu6050.cpp.
{
  return I2C::Bus::writeRegister(kDeviceAddress, static_cast<uint8_t>(reg),
                                 data);
}
References kDeviceAddress, and I2C::Bus::writeRegister().
writeSleep()
void MPU6050::Device::writeSleep (bool sleep) private
Put the MPU6050 to sleep or wake up.
Parameters
sleep 0 = awake, 1 = sleep
Definition at line 91 of file mpu6050.cpp.
{
  writeBit(MPU6050::Register::PWRMGMT1, kAccelerometerRegisterPwrMgmt1_SleepBit,
           sleep);
}
References kAccelerometerRegisterPwrMgmt1_SleepBit, and MPU6050::PWRMGMT1.
Referenced by sleep(), and wakeUp().
Member Data Documentation
acc_scale_
uint32_t MPU6050::Device::acc_scale_ = 0 private
Acceleration scale.
Definition at line 255 of file mpu6050.h.
acceleration_
AxisAccel MPU6050::Device::acceleration_ private
Acceleration data.
Definition at line 254 of file mpu6050.h.
Referenced by getAcceleration().
config_
ConfigMPU6050 MPU6050::Device::config_ private
Configuration of the MPU6050.
Definition at line 253 of file mpu6050.h.
gyro_scale_
double MPU6050::Device::gyro_scale_ = 0 private
Gyroscope scale.
Definition at line 256 of file mpu6050.h.
The documentation for this class was generated from the following files:
components/mpu6050/include/mpu6050.h
components/mpu6050/mpu6050.cpp