Can2Cloud: I2C::Bus Class Reference
I2C::Bus Class Reference
#include <i2c.h>
Public Member Functions
Bus (i2c_port_t port, gpio_num_t sda, gpio_num_t scl, uint32_t clk_speed)
Construct a new Bus object.
virtual ~Bus ()
Destroy the Bus object. It will delete the I2C controller.
esp_err_t init ()
A initialization function to configure the I2C controller.
esp_err_t writeRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t tx_data)
Method to write a byte to a register. It will write a byte to a register of a device connected to the I2C bus.
esp_err_t writeRegisterMultipleBytes (uint8_t dev_addr, uint8_t reg_addr, uint8_t *tx_data, uint32_t length)
Method to write multiple bytes to a register. It will write multiple bytes to a register of a device connected to the I2C bus. TODO: Implement this method.
esp_err_t writeBitRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t bit_num, bool data)
Method to write a bit to a register. It will write a bit to a register of a device connected to the I2C bus.
esp_err_t writeBitField (uint8_t dev_addr, uint8_t reg_addr, uint8_t start_bit, uint8_t length, uint8_t data)
Method to write a bit field to a register. It will write a bit field to a register of a device connected to the I2C bus.
uint8_t readRegister (uint8_t dev_addr, uint8_t reg_addr)
method to read a byte from a register. It will read a byte from a register of a device connected to the I2C bus.
esp_err_t readRegisterMultipleBytes (uint8_t dev_addr, uint8_t reg_addr, uint8_t *rx_data, uint32_t length)
Method to read multiple bytes from a register. It will read multiple bytes from a register of a device connected to the I2C bus.
uint8_t readBitFieldFromRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t start_bit, uint8_t length)
Method to read a bit field from a register. It will read a bit field from a register of a device connected to the I2C bus.
esp_err_t readWord (uint8_t dev_addr, uint8_t reg_addr, uint16_t *rx_data)
Method to read a word from a register. It will read a word from a register of a device connected to the I2C bus.
gpio_num_t getSda () const
Get the sda pin number.
gpio_num_t getScl () const
Get the scl pin number.
uint32_t getClkSpeed () const
Get the Clk Speed value.
Private Attributes
i2c_config_t config_
I2C configuration.
i2c_port_t port_
I2C port.
gpio_num_t sda_
SDA pin.
gpio_num_t scl_
SCL pin.
uint32_t clk_speed_
Clock speed.
Detailed Description
Definition at line 30 of file i2c.h.
Constructor & Destructor Documentation
Bus()
I2C::Bus::Bus (i2c_port_t port, gpio_num_t sda, gpio_num_t scl, uint32_t clk_speed)
Construct a new Bus object.
Parameters
port port number of the I2C controller
sda pin number of the SDA pin
scl pin number of the SCL pin
clk_speed clock speed of the I2C bus
Definition at line 3 of file i2c.cpp.
    : port_(port), sda_(sda), scl_(scl), clk_speed_(clk_speed) {
  if (init() != ESP_OK) {
    ESP_LOGE("I2C", "Failed to initialize I2C bus");
  } else {
    ESP_LOGI("I2C", "Initialized I2C bus");
  }
}
References init().
~Bus()
I2C::Bus::~Bus () virtual
Destroy the Bus object. It will delete the I2C controller.
Definition at line 13 of file i2c.cpp.
{ i2c_driver_delete(port_); }
Member Function Documentation
getClkSpeed()
uint32_t I2C::Bus::getClkSpeed () const inline
Get the Clk Speed value.
Returns
uint32_t Clk Speed value
Definition at line 185 of file i2c.h.
{ return clk_speed_; };
References clk_speed_.
getScl()
gpio_num_t I2C::Bus::getScl () const inline
Get the scl pin number.
Returns
gpio_num_t scl pin number
Definition at line 178 of file i2c.h.
{ return scl_; };
References scl_.
getSda()
gpio_num_t I2C::Bus::getSda () const inline
Get the sda pin number.
Returns
gpio_num_t sda pin number
Definition at line 170 of file i2c.h.
{ return sda_; };
References sda_.
init()
esp_err_t I2C::Bus::init ()
A initialization function to configure the I2C controller.
Returns
esp_err_t
ESP_OK: success
ESP_FAIL: fail
Definition at line 15 of file i2c.cpp.
                       {
  config_.mode = I2C_MODE_MASTER;
  config_.sda_io_num = sda_;
  config_.scl_io_num = scl_;
  config_.sda_pullup_en = GPIO_PULLUP_ENABLE;
  config_.scl_pullup_en = GPIO_PULLUP_ENABLE;
  config_.master.clk_speed = clk_speed_;
  config_.clk_flags = 0;
  esp_err_t err = ESP_OK;
  err |= i2c_param_config(port_, &config_);
  err |= i2c_driver_install(port_, config_.mode, 0, 0, 0);
  return err;
}
Referenced by Bus().
readBitFieldFromRegister()
uint8_t I2C::Bus::readBitFieldFromRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t start_bit, uint8_t length)
Method to read a bit field from a register. It will read a bit field from a register of a device connected to the I2C bus.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
start_bit number of the start bit to be read.
length number of bits to be read.
Returns
uint8_t data read from the register.
Definition at line 70 of file i2c.cpp.
{
  uint8_t data = readRegister(dev_addr, reg_addr);
  return (data >> start_bit) & ((1U << length) - 1);
}
Referenced by MPU6050::Device::readBitField().
readRegister()
uint8_t I2C::Bus::readRegister (uint8_t dev_addr, uint8_t reg_addr)
method to read a byte from a register. It will read a byte from a register of a device connected to the I2C bus.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
Returns
uint8_t data read from the register.
Definition at line 33 of file i2c.cpp.
{
  uint8_t rx_data;
  i2c_master_write_read_device(port_, dev_addr, &reg_addr, 1, &rx_data, 1,
                               1000 / portTICK_PERIOD_MS);
  return rx_data;
}
Referenced by MPU6050::Device::readRegister().
readRegisterMultipleBytes()
esp_err_t I2C::Bus::readRegisterMultipleBytes (uint8_t dev_addr, uint8_t reg_addr, uint8_t * rx_data, uint32_t length)
Method to read multiple bytes from a register. It will read multiple bytes from a register of a device connected to the I2C bus.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
rx_data pointer to the array where the data will be stored.
length number of bytes to be read.
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 50 of file i2c.cpp.
{
  return i2c_master_write_read_device(port_, dev_addr, &reg_addr, 1, rx_data,
                                      length, 1000 / portTICK_PERIOD_MS);
}
Referenced by MPU6050::Device::readBlock().
readWord()
esp_err_t I2C::Bus::readWord (uint8_t dev_addr, uint8_t reg_addr, uint16_t * rx_data)
Method to read a word from a register. It will read a word from a register of a device connected to the I2C bus.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
rx_data pointer to the variable where the data will be stored.
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 58 of file i2c.cpp.
{
  uint8_t data[2];
  esp_err_t err = i2c_master_write_read_device(
      port_, dev_addr, &reg_addr, 1, data, 2, 1000 / portTICK_PERIOD_MS);
  *rx_data = (data[0] << 8) | data[1];
  return err;
}
writeBitField()
esp_err_t I2C::Bus::writeBitField (uint8_t dev_addr, uint8_t reg_addr, uint8_t start_bit, uint8_t length, uint8_t data)
Method to write a bit field to a register. It will write a bit field to a register of a device connected to the I2C bus.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
start_bit number of the start bit to be written.
length number of bits to be written.
data data to be written.
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 87 of file i2c.cpp.
{
  int8_t register_value = readRegister(dev_addr, reg_addr);
  uint8_t bit_mask = ((1U << length) - 1);
  register_value &= ~(bit_mask << start_bit);
  register_value |= (data << start_bit);
  return writeRegister(dev_addr, reg_addr, register_value);
}
Referenced by MPU6050::Device::writeBitField().
writeBitRegister()
esp_err_t I2C::Bus::writeBitRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t bit_num, bool data)
Method to write a bit to a register. It will write a bit to a register of a device connected to the I2C bus.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
bit_num number of the bit to be written.
data data to be written.
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 77 of file i2c.cpp.
{
  uint8_t register_value = readRegister(dev_addr, reg_addr);
  register_value = (data) ? (register_value | (1 << bit_num))
                          : (register_value & ~(1 << bit_num));
  return writeRegister(dev_addr, reg_addr, register_value);
}
Referenced by MPU6050::Device::writeBit().
writeRegister()
esp_err_t I2C::Bus::writeRegister (uint8_t dev_addr, uint8_t reg_addr, uint8_t tx_data)
Method to write a byte to a register. It will write a byte to a register of a device connected to the I2C bus.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
tx_data data to be written.
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Definition at line 42 of file i2c.cpp.
{
  uint8_t data[2] = {reg_addr, tx_data};
  return i2c_master_write_to_device(port_, dev_addr, data, 2,
                                    1000 / portTICK_PERIOD_MS);
}
Referenced by MPU6050::Device::writeRegister().
writeRegisterMultipleBytes()
esp_err_t I2C::Bus::writeRegisterMultipleBytes (uint8_t dev_addr, uint8_t reg_addr, uint8_t * tx_data, uint32_t length)
Method to write multiple bytes to a register. It will write multiple bytes to a register of a device connected to the I2C bus. TODO: Implement this method.
Parameters
dev_addr address of the device.
reg_addr address of the register target.
tx_data data to be written.
length number of bytes to be written.
Returns
esp_err_t
- ESP_OK: success
- ESP_FAIL: fail
Member Data Documentation
clk_speed_
uint32_t I2C::Bus::clk_speed_ private
Clock speed.
Definition at line 36 of file i2c.h.
Referenced by getClkSpeed().
config_
i2c_config_t I2C::Bus::config_ private
I2C configuration.
Definition at line 32 of file i2c.h.
port_
i2c_port_t I2C::Bus::port_ private
I2C port.
Definition at line 33 of file i2c.h.
scl_
gpio_num_t I2C::Bus::scl_ private
SCL pin.
Definition at line 35 of file i2c.h.
Referenced by getScl().
sda_
gpio_num_t I2C::Bus::sda_ private
SDA pin.
Definition at line 34 of file i2c.h.
Referenced by getSda().
The documentation for this class was generated from the following files:
components/mpu6050/include/i2c.h
components/mpu6050/i2c.cpp