Can2Cloud: main/main_receive.cpp File Reference
main_receive.cpp File Reference
#include <stdio.h>
#include "mcp2515.h"
#include "sim900.h"
Functions
void send_task (void *pvParameters)
void receive_task (void *pvParameters)
void app_main (void)
Variables
QueueHandle_t queue_can
SIM900::Dev node ("zap.vivo.com.br", "vivo", "vivo")
const char * token = "01d619fe-f681-4f69-a9b6-b0ab57ab684b"
Function Documentation
app_main()
void app_main (void)
Definition at line 12 of file main_receive.cpp.
{
  node.init();
  node.SetPrompt();
  node.CIPStart("TCP", "api.tago.io", "80");
  queue_can = xQueueCreate(5, sizeof(CanMessage));
  xTaskCreatePinnedToCore(receive_task, "Receive Task", 2048, NULL, 1, NULL,
                          PRO_CPU_NUM);
  xTaskCreatePinnedToCore(send_task, "Send Task", 2048 + 1024, NULL, 1, NULL,
                          APP_CPU_NUM);
}
References SIM900::Dev::CIPStart(), SIM900::Dev::init(), node, queue_can, receive_task(), send_task(), and SIM900::Dev::SetPrompt().
receive_task()
void receive_task (void * pvParameters)
Definition at line 46 of file main_receive.cpp.
{
  MCP2515::ConfigModule configModule;
  MCP2515::Device node(configModule);
  CanMessage canRes;
  while (1) {
    node.readMessage(canRes);
    xQueueSend(queue_can, &canRes, 1000 / portTICK_PERIOD_MS);
    vTaskDelay(100 / portTICK_PERIOD_MS);
  }
}
References configModule, node, and queue_can.
Referenced by app_main().
send_task()
void send_task (void * pvParameters)
Definition at line 23 of file main_receive.cpp.
{
  CanMessage canData;
  int16_t x, y, z;
  while (1) {
    if (xQueueReceive(queue_can, &canData, portMAX_DELAY) == pdPASS) {
      x = canData.data[0] << 8;
      x |= canData.data[1];
      y = canData.data[2] << 8;
      y |= canData.data[3];
      z = canData.data[4] << 8;
      z |= canData.data[5];
      const char* x_buffer = std::to_string(x).c_str();
      const char* y_buffer = std::to_string(y).c_str();
      const char* z_buffer = std::to_string(z).c_str();
      node.CIPSend(token, x_buffer, y_buffer, z_buffer);
      vTaskDelay(100 / portTICK_PERIOD_MS);
    }
  }
}
References SIM900::Dev::CIPSend(), CanMessage::data, node, queue_can, and token.
Referenced by app_main().
Variable Documentation
node
SIM900::Dev node("zap.vivo.com.br", "vivo", "vivo") ("zap.vivo.com.br" , "vivo" , "vivo")
Referenced by app_main(), receive_task(), send_task(), and vTaskCan().
queue_can
QueueHandle_t queue_can
Definition at line 6 of file main_receive.cpp.
Referenced by app_main(), receive_task(), and send_task().
token
const char* token = "01d619fe-f681-4f69-a9b6-b0ab57ab684b"
Definition at line 10 of file main_receive.cpp.
Referenced by send_task().