Can2Cloud: main/main_send.cpp File Reference
main_send.cpp File Reference
#include <stdio.h>
#include <iostream>
#include "can.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"
#include "mcp2515.h"
#include "mpu6050.h"
Functions
void vTaskAccel (void *pvParameters)
void vTaskCan (void *pvParameters)
void app_main (void)
Example application for sending CAN messages.
Variables
QueueHandle_t accQueue
struct MPU6050::ConfigMPU6050 config
struct MCP2515::ConfigModule configModule
Function Documentation
app_main()
void app_main (void)
Example application for sending CAN messages.
Definition at line 35 of file main_send.cpp.
{
  accQueue = xQueueCreate(5, sizeof(MPU6050::AxisAccel));
  // node.setNormalMode(); // Call by the constructor
  /* CanMessage canMsg;
  canMsg.identifier = 0x123;
  canMsg.data_length_code = 8;
  canMsg.data[0] = 0x01;
  canMsg.data[1] = 0x02;
  canMsg.data[2] = 0x03;
  canMsg.data[3] = 0x04;
  canMsg.data[4] = 0x05;
  canMsg.data[5] = 0x06;
  canMsg.data[6] = 0x0F;
  canMsg.data[7] = 0x08;
  int i = 0;
  while (1) {
    node.sendMessage(canMsg);
    std::cout << "Send ok !! " << std::endl;
    std::cout << "i = " << i << std::endl;
    i++;
    canMsg.data[0] = i;
    vTaskDelay(300 / portTICK_PERIOD_MS);
  } */
  xTaskCreate(vTaskAccel, "TaskAccel", 2048, NULL, 1, NULL);
  xTaskCreate(vTaskCan, "TaskCan", 2048, NULL, 1, NULL);
}
References accQueue, vTaskAccel(), and vTaskCan().
vTaskAccel()
void vTaskAccel (void * pvParameters)
Definition at line 64 of file main_send.cpp.
{
  MPU6050::Device device(config);
  while (1) {
    MPU6050::AxisAccel const& axis = device.getAcceleration();
    xQueueSend(accQueue, &axis, portMAX_DELAY);
    vTaskDelay(100 / portTICK_PERIOD_MS);
  }
}
References accQueue, config, and MPU6050::Device::getAcceleration().
Referenced by app_main().
vTaskCan()
void vTaskCan (void * pvParameters)
Definition at line 73 of file main_send.cpp.
{
  MCP2515::Device node(configModule);
  CanMessage canMsg;
  MPU6050::AxisAccel acc;
  while (1) {
    if (xQueueReceive(accQueue, &acc, portMAX_DELAY) == pdTRUE) {
      std::cout << "x = " << acc.x << std::endl;
      std::cout << "y = " << acc.y << std::endl;
      std::cout << "z = " << acc.z << std::endl;
      canMsg.identifier = 0x123;
      canMsg.data_length_code = 8;
      canMsg.data[0] = acc.x >> 8;
      canMsg.data[1] = acc.x;
      canMsg.data[2] = acc.y >> 8;
      canMsg.data[3] = acc.y;
      canMsg.data[4] = acc.z >> 8;
      canMsg.data[5] = acc.z;
      node.sendMessage(canMsg);
      std::cout << "Send ok !! " << std::endl;
    }
    vTaskDelay(100 / portTICK_PERIOD_MS);
  }
}
References accQueue, configModule, CanMessage::data, CanMessage::data_length_code, CanMessage::identifier, node, MPU6050::AxisAccel::x, MPU6050::AxisAccel::y, and MPU6050::AxisAccel::z.
Referenced by app_main().
Variable Documentation
accQueue
QueueHandle_t accQueue
Definition at line 24 of file main_send.cpp.
Referenced by app_main(), vTaskAccel(), and vTaskCan().
config
struct MPU6050::ConfigMPU6050 config
Definition at line 28 of file main_send.cpp.
Referenced by MCP2515::Device::Device(), MCP2515::Device::setBitrate(), and vTaskAccel().
configModule
struct MCP2515::ConfigModule configModule
Definition at line 29 of file main_send.cpp.
Referenced by receive_task(), and vTaskCan().